#! /bin/sh

## Copyright (C) 2023-2023 Aditya Sharma
##
## BSPWM configuration for LEGION



## Autostart ------------------------------------------------ #

pgrep -x sxhkd > /dev/null || sxhkd &  # Key-Bindings
picom &                                # Compositor
nitrogen --restore &		       # Wallpaper
dunst -c ~/.config/dunst/dunstrc &     # Notify
~/.config/polybar/launch.sh &          # Polybar



# cursor correction
xsetroot -cursor_name left_ptr &


## Variables ------------------------------------------------ #

TERMINAL    = 'st'
BORDER      = '2'
SPLIT_RATIO = '0.50'
WIN_GAP     = '10'


## Configurations ------------------------------------------- #

#bspc monitor -d 1 2 3 4 5
bspc monitor -d '' '' '' '' '' '' '' ''

bspc config border_width         "$BORDER" 
bspc config window_gap           "$WIN_GAP"
bspc config split_ratio          "$SPLIT_RATIO"

bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

bspc config focused_border_color "#8fbcbb" 
bspc config normal_border_color "#4c566a"
bspc config active_border_color "#B4E3AD"
bspc config presel_feedback_color "#E5A3A1"



## Rules ---------------------------------------------------- #


bspc rule -a <WM_CLASS> state=floating rectangle=300x300+600+250
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Terminal
bspc rule -a '$TERMINAL' desktop='^1' follow=on focus=on
bspc rule -a xfce4-terminal desktop='^1' follow=on focus=on

# WebBrowser
bspc rule -a firefox desktop='^2' follow=on focus=on
bspc rule -a chromium desktop='^2' follow=on focus=on

# FileManager
bspc rule -a Pcmanfm desktop='^3' follow=on focus=on
bspc rule -a Nemo desktop='^3' follow=on focus=on

# System Settings
bspc rule -a GParted desktop='^8' follow=on focus=on
declare -a settings=(Lxappearance Lxtask Lxrandr Arandr \
System-config-printer.py Pavucontrol Exo-helper-1 \
Xfce4-power-manager-settings)
for i in ${settings[@]}; do
   bspc rule -a $i desktop='^8' state=floating follow=on focus=on; done

# Always Floating Apps
declare -a floating=(alacritty-float Pcmanfm Thunar Onboard Yad 'Firefox:Places' \
Viewnior feh Nm-connection-editor)
for i in ${floating[@]}; do
   bspc rule -a $i state=floating follow=on focus=on; done

