#! /bin/sh

#
#                 ░█▀▄░█▀▀░█▀█░█░█░█▄█
#                 ░█▀▄░▀▀█░█▀▀░█▄█░█░█
#                 ░▀▀░░▀▀▀░▀░░░▀░▀░▀░▀
#

#$HOME/.scripts/custom-autostart

#nm-applet &
xsetroot -cursor_name left_ptr
sxhkd &
picom --experimental-backends &
nitrogen --restore
wmname LG3D &
lxpolkit &
xset -dpms s off & # disable screen blanking
dropbox &
dunst &
nautilus --gapplication-service &
#~/.config/polybar/scripts/launch-polybar.sh &


# Swallow

#nohup pidof $HOME/.scripts/bspswallow || $HOME/.scripts/bspswallow &
pgrep bspswallow || nohup ~/.scripts/bspswallow &

# Workspaces

bspc monitor LVDS-1 -d 1 2 3 4 5 6 7 8 9 
bspc config border_width         2
bspc config window_gap          10
bspc config top_padding 0
bspc config focus_follows_pointer true
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc pointer -g focus

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mpv state=floating
bspc rule -a Sxiv state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#### BSPWM coloring ####
bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"
bspc config urgent_border_color "#dd2727"


# Default state/workspace for applications
bspc rule -a Chromium desktop='^2'
bspc rule -a discord desktop='^7'
bspc rule -a mplayer2 state=floating
bspc rule -a nomacs state=floating
bspc rule -a nomacs state=floating
bspc rule -a "Image Lounge" state=floating
bspc rule -a Zathura state=tiled
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc config pointer_modifier mod4

#sleep 0.69

# Autostart applications:

# Start Polyba   
~/.config/polybar/scripts/launch-polybar.sh &
picom --config /home/dxg/.config/picom/picom.conf
# Start floating kitty terminal
#bspc rule -a \* -o state=floating && sleep 0.015 ; kitty -e $SHELL -c "$HOME/.config/neofetch/launch-neofetch.sh && $SHELL" &
 

# Start firefox
#/bin/bash -c "bspc desktop -f '^2' --follow ; bspc rule -a \* -o node=@$(bspc query -D -d):.focused split_dir=south follow=off ; firefox file:///home/$USER/.config/startpage/index.html &" &
bspc desktop -f '^2' --follow &

